# Generated by Django 4.2.4 on 2023-08-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Telephone', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('BirthDate', models.DateField()),
                ('Address', models.CharField(max_length=200)),
                ('Telephone', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('BirthDate', models.DateField()),
                ('Address', models.CharField(max_length=200)),
                ('Telephone', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.department')),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.department')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='RenderedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.appointment')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service')),
            ],
            options={
                'db_table': 'RenderedService',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Medication', models.CharField(max_length=200)),
                ('Approved', models.CharField(max_length=50)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.appointment')),
            ],
            options={
                'db_table': 'Prescription',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.department')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
            ],
            options={
                'db_table': 'Job',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RenderedService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.renderedservice')),
            ],
            options={
                'db_table': 'Invoice',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.room'),
        ),
    ]
