name: Python Basics validation

on:
  push:
    branches:
      - main
    paths:
      - '0-python-basics/**'
  pull_request:
    branches:
      - main
    paths:
      - '0-python-basics/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./0-python-basics
    env:
      python-version: "3.11"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --max-complexity=10 --show-source --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest
